{
 "title": "Multicontainer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Disk free space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$C - 200000000", "type": "math" }
   ]
  },
  {
   "title": "Disk usage in the moment",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name=\"test-env\"}[$__rate_interval])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{name=\"test-env\"}[$__rate_interval])",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Disk reads/writes count total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_fs_reads_total{name=\"test-env\", device=\"/dev/nvme0n1\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "container_fs_writes_total{name=\"test-env\", device=\"/dev/nvme0n1\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Disk reads/writes bytes total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{name=\"test-env\"}",
     "legendFormat": "reads"
    },
    {
     "expr": "container_fs_writes_bytes_total{name=\"test-env\"}",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network transmit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom exported metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(s21_container_cpu_usage_seconds_total[$__rate_interval]) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running containers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{image!=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total memory usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total memory usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[$__rate_interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "s21_container_memory_usage_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "s21_container_memory_free_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FS usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "s21_container_fs_usage_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "FS free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "s21_container_fs_free_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}