{
 "title": "container",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "container_fs_io_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name=\"test-env\"} - container_memory_working_set_bytes{id=~\"/docker/.{10,}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name=\"test-env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS space free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_blkio_device_usage_total{name=\"test-env\"}",
     "legendFormat": "__auto"
    },
    { "expression": "3*1000*1024*1024 - $A", "type": "math" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=~\"/docker/.{10,}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS i/o",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{name=\"test-env\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"test-env\"}[10s]) * 100",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}